[package]
name = "llmcore_v1"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.21.3"
pest = "2.8.1"
pest_derive = "2.8.1"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
